name: Test and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 🚀 Trigger quando si fa push su 'main'
  pull_request: # 🔎 Controlla i test anche nelle PR prima di unire i cambiamenti
  workflow_dispatch: # 📌 Permette l'esecuzione manuale

permissions:
  contents: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test # 🔥 Se i test falliscono, il deploy non parte!

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test # ✅ Il deploy avviene solo se i test passano

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
